'io':
  'featuresheets':
    'example_sheet_tsv':
      'description': 'Example TSV file for feature metadata'
      'path': 'example_data/example_featuresheet.tsv'
      'index': 'gene name'

  'samplesheets':
    'example_sheet_googleapi':
      'description': 'Example Google Spreadsheet for cell metadata'
      'url': 'https://docs.google.com/spreadsheets/d/15OKOC48WZYFUQvYl9E7qEsR6AjqE4_BW7qcCsjJAD6w'
      'client_id_filename': 'example_data/example_google_client_id.json'
      'client_secret_filename': 'example_data/example_google_client_secret.json'
      'sheet': 'cells'
      'cells': 'rows'
    'example_sheet_tsv':
      'description': 'Example TSV file for cell metadata'
      'path': 'example_data/example_sample_table - sequenced.tsv'
      'cells': 'rows'

  'count_tables':
    'example_table_tsv':
      'description': 'Example table of gene counts (not normalized)'
      'path': 'example_data/example_counts_table.tsv'
      'cells': 'columns'
      'normalized': no
      'spikeins':
         - 'ERCC-00002'
         - 'ERCC-00003'
         - 'ERCC-00004'
         - 'ERCC-00007'
         - 'ERCC-00009'
         - 'ERCC-00012'
         - 'ERCC-00013'
         - 'ERCC-00014'
         - 'ERCC-00016'
         - 'ERCC-00017'
         - 'ERCC-00018'
         - 'ERCC-00019'
         - 'ERCC-00022'
         - 'ERCC-00023'
         - 'ERCC-00024'
         - 'ERCC-00025'
         - 'ERCC-00028'
         - 'ERCC-00031'
         - 'ERCC-00033'
         - 'ERCC-00034'
         - 'ERCC-00035'
         - 'ERCC-00039'
         - 'ERCC-00040'
         - 'ERCC-00041'
         - 'ERCC-00042'
         - 'ERCC-00043'
         - 'ERCC-00044'
         - 'ERCC-00046'
         - 'ERCC-00048'
         - 'ERCC-00051'
         - 'ERCC-00053'
         - 'ERCC-00054'
         - 'ERCC-00057'
         - 'ERCC-00058'
         - 'ERCC-00059'
         - 'ERCC-00060'
         - 'ERCC-00061'
         - 'ERCC-00062'
         - 'ERCC-00067'
         - 'ERCC-00069'
         - 'ERCC-00071'
         - 'ERCC-00073'
         - 'ERCC-00074'
         - 'ERCC-00075'
         - 'ERCC-00076'
         - 'ERCC-00077'
         - 'ERCC-00078'
         - 'ERCC-00079'
         - 'ERCC-00081'
         - 'ERCC-00083'
         - 'ERCC-00084'
         - 'ERCC-00085'
         - 'ERCC-00086'
         - 'ERCC-00092'
         - 'ERCC-00095'
         - 'ERCC-00096'
         - 'ERCC-00097'
         - 'ERCC-00098'
         - 'ERCC-00099'
         - 'ERCC-00104'
         - 'ERCC-00108'
         - 'ERCC-00109'
         - 'ERCC-00111'
         - 'ERCC-00112'
         - 'ERCC-00113'
         - 'ERCC-00116'
         - 'ERCC-00117'
         - 'ERCC-00120'
         - 'ERCC-00123'
         - 'ERCC-00126'
         - 'ERCC-00128'
         - 'ERCC-00130'
         - 'ERCC-00131'
         - 'ERCC-00134'
         - 'ERCC-00136'
         - 'ERCC-00137'
         - 'ERCC-00138'
         - 'ERCC-00142'
         - 'ERCC-00143'
         - 'ERCC-00144'
         - 'ERCC-00145'
         - 'ERCC-00147'
         - 'ERCC-00148'
         - 'ERCC-00150'
         - 'ERCC-00154'
         - 'ERCC-00156'
         - 'ERCC-00157'
         - 'ERCC-00158'
         - 'ERCC-00160'
         - 'ERCC-00162'
         - 'ERCC-00163'
         - 'ERCC-00164'
         - 'ERCC-00165'
         - 'ERCC-00168'
         - 'ERCC-00170'
         - 'ERCC-00171'
      'other':
         - 'NIST_ConsensusVector'
         - '__no_feature'
         - '__ambiguous'
         - '__too_low_aQual'
         - '__not_aligned'
         - '__alignment_not_unique'

    'example_table_tsv_split':
      'description': 'Example table of gene counts (not normalized)'
      'path':
        - 'example_data/example_counts_table_split1.tsv'
        - 'example_data/example_counts_table_split2.tsv'
      'cells': 'columns'
      'normalized': no
      'spikeins':
         - 'ERCC-00002'
         - 'ERCC-00003'
         - 'ERCC-00004'
         - 'ERCC-00007'
         - 'ERCC-00009'
         - 'ERCC-00012'
         - 'ERCC-00013'
         - 'ERCC-00014'
         - 'ERCC-00016'
         - 'ERCC-00017'
         - 'ERCC-00018'
         - 'ERCC-00019'
         - 'ERCC-00022'
         - 'ERCC-00023'
         - 'ERCC-00024'
         - 'ERCC-00025'
         - 'ERCC-00028'
         - 'ERCC-00031'
         - 'ERCC-00033'
         - 'ERCC-00034'
         - 'ERCC-00035'
         - 'ERCC-00039'
         - 'ERCC-00040'
         - 'ERCC-00041'
         - 'ERCC-00042'
         - 'ERCC-00043'
         - 'ERCC-00044'
         - 'ERCC-00046'
         - 'ERCC-00048'
         - 'ERCC-00051'
         - 'ERCC-00053'
         - 'ERCC-00054'
         - 'ERCC-00057'
         - 'ERCC-00058'
         - 'ERCC-00059'
         - 'ERCC-00060'
         - 'ERCC-00061'
         - 'ERCC-00062'
         - 'ERCC-00067'
         - 'ERCC-00069'
         - 'ERCC-00071'
         - 'ERCC-00073'
         - 'ERCC-00074'
         - 'ERCC-00075'
         - 'ERCC-00076'
         - 'ERCC-00077'
         - 'ERCC-00078'
         - 'ERCC-00079'
         - 'ERCC-00081'
         - 'ERCC-00083'
         - 'ERCC-00084'
         - 'ERCC-00085'
         - 'ERCC-00086'
         - 'ERCC-00092'
         - 'ERCC-00095'
         - 'ERCC-00096'
         - 'ERCC-00097'
         - 'ERCC-00098'
         - 'ERCC-00099'
         - 'ERCC-00104'
         - 'ERCC-00108'
         - 'ERCC-00109'
         - 'ERCC-00111'
         - 'ERCC-00112'
         - 'ERCC-00113'
         - 'ERCC-00116'
         - 'ERCC-00117'
         - 'ERCC-00120'
         - 'ERCC-00123'
         - 'ERCC-00126'
         - 'ERCC-00128'
         - 'ERCC-00130'
         - 'ERCC-00131'
         - 'ERCC-00134'
         - 'ERCC-00136'
         - 'ERCC-00137'
         - 'ERCC-00138'
         - 'ERCC-00142'
         - 'ERCC-00143'
         - 'ERCC-00144'
         - 'ERCC-00145'
         - 'ERCC-00147'
         - 'ERCC-00148'
         - 'ERCC-00150'
         - 'ERCC-00154'
         - 'ERCC-00156'
         - 'ERCC-00157'
         - 'ERCC-00158'
         - 'ERCC-00160'
         - 'ERCC-00162'
         - 'ERCC-00163'
         - 'ERCC-00164'
         - 'ERCC-00165'
         - 'ERCC-00168'
         - 'ERCC-00170'
         - 'ERCC-00171'
      'other':
         - 'NIST_ConsensusVector'
         - '__no_feature'
         - '__ambiguous'
         - '__too_low_aQual'
         - '__not_aligned'
         - '__alignment_not_unique'

    'example_PBMC':
      'description': 'Example table of gene counts from PBMCs (not normalized)'
      'cells': 'columns'
      'normalized': no
      'path': 'example_data/counts_table_PBMC.tsv'
      'spikeins':
         - 'ERCC-00002'
         - 'ERCC-00003'
         - 'ERCC-00004'
         - 'ERCC-00009'
         - 'ERCC-00019'
         - 'ERCC-00022'
         - 'ERCC-00025'
         - 'ERCC-00035'
         - 'ERCC-00042'
         - 'ERCC-00043'
         - 'ERCC-00044'
         - 'ERCC-00046'
         - 'ERCC-00048'
         - 'ERCC-00051'
         - 'ERCC-00053'
         - 'ERCC-00059'
         - 'ERCC-00060'
         - 'ERCC-00062'
         - 'ERCC-00071'
         - 'ERCC-00074'
         - 'ERCC-00076'
         - 'ERCC-00078'
         - 'ERCC-00079'
         - 'ERCC-00084'
         - 'ERCC-00092'
         - 'ERCC-00095'
         - 'ERCC-00096'
         - 'ERCC-00108'
         - 'ERCC-00111'
         - 'ERCC-00112'
         - 'ERCC-00113'
         - 'ERCC-00116'
         - 'ERCC-00130'
         - 'ERCC-00131'
         - 'ERCC-00136'
         - 'ERCC-00144'
         - 'ERCC-00145'
         - 'ERCC-00148'
         - 'ERCC-00160'
         - 'ERCC-00162'
         - 'ERCC-00163'
         - 'ERCC-00165'
         - 'ERCC-00170'
         - 'ERCC-00171'
      'other':
         - '__no_feature'
         - '__ambiguous'
         - '__alignment_not_unique'

    'example_PBMC_sparse':
      'description': 'Example table of gene counts from PBMCs (not normalized)'
      'cells': 'columns'
      'normalized': no
      'path': 'example_data/counts_table_PBMC_sparse.npz'
      'spikeins':
         - 'ERCC-00002'
         - 'ERCC-00003'
         - 'ERCC-00004'
         - 'ERCC-00009'
         - 'ERCC-00019'
         - 'ERCC-00022'
         - 'ERCC-00025'
         - 'ERCC-00035'
         - 'ERCC-00042'
         - 'ERCC-00043'
         - 'ERCC-00044'
         - 'ERCC-00046'
         - 'ERCC-00048'
         - 'ERCC-00051'
         - 'ERCC-00053'
         - 'ERCC-00059'
         - 'ERCC-00060'
         - 'ERCC-00062'
         - 'ERCC-00071'
         - 'ERCC-00074'
         - 'ERCC-00076'
         - 'ERCC-00078'
         - 'ERCC-00079'
         - 'ERCC-00084'
         - 'ERCC-00092'
         - 'ERCC-00095'
         - 'ERCC-00096'
         - 'ERCC-00108'
         - 'ERCC-00111'
         - 'ERCC-00112'
         - 'ERCC-00113'
         - 'ERCC-00116'
         - 'ERCC-00130'
         - 'ERCC-00131'
         - 'ERCC-00136'
         - 'ERCC-00144'
         - 'ERCC-00145'
         - 'ERCC-00148'
         - 'ERCC-00160'
         - 'ERCC-00162'
         - 'ERCC-00163'
         - 'ERCC-00165'
         - 'ERCC-00170'
         - 'ERCC-00171'
      'other':
         - '__no_feature'
         - '__ambiguous'
         - '__alignment_not_unique'

